export const DEMO_OVERVIEW = {
  totalUsers: 1284,
  activeUsers: 847,
  totalSessions: 3621,
  monthlyRevenue: 45800,
};

export const DEMO_USER_DISTRIBUTION = {
  total: 1284,
  coaches: 342,
  athletes: 942,
};

export const DEMO_REVENUE_TREND = [
  { month: "Jan", revenue: 32000 },
  { month: "Feb", revenue: 28500 },
  { month: "Mar", revenue: 35800 },
  { month: "Apr", revenue: 41200 },
  { month: "May", revenue: 38900 },
  { month: "Jun", revenue: 45800 },
];

export const DEMO_RECENT_ACTIVITY = [
  {
    user_avatar_url: null,
    name: "Sarah Johnson",
    time_ago: "2 minutes ago",
    message: "completed a new session booking",
    activity_date: "May 24, 2026",
  },
  {
    user_avatar_url: null,
    name: "Mike Chen",
    time_ago: "15 minutes ago",
    message: "subscribed to Premium plan",
    activity_date: "May 24, 2026",
  },
  {
    user_avatar_url: null,
    name: "Emily Davis",
    time_ago: "1 hour ago",
    message: "earned 'Marathon' badge",
    activity_date: "May 24, 2026",
  },
  {
    user_avatar_url: null,
    name: "Alex Rivera",
    time_ago: "3 hours ago",
    message: "purchased from marketplace",
    activity_date: "May 23, 2026",
  },
  {
    user_avatar_url: null,
    name: "Lisa Thompson",
    time_ago: "5 hours ago",
    message: "updated profile information",
    activity_date: "May 23, 2026",
  },
];

export const DEMO_BOOKING_LIST = {
  data: {
    data: [
      { id: "1", athlete_name: "James Wilson", athlete_avatar: "", session_type: "One-on-One", coach_name: "Sarah Johnson (Strength)", date_time: "May 25, 2026 10:00 AM", status: "UPCOMING", appointment_date: "2026-05-25", session_time: "10:00", duration_minutes: 60, location: "Studio A", description: null, notes: "", created_at: "2026-05-20" },
      { id: "2", athlete_name: "Maria Garcia", athlete_avatar: "", session_type: "Group Class", coach_name: "Mike Chen (Yoga)", date_time: "May 25, 2026 02:00 PM", status: "CONFIRMED", appointment_date: "2026-05-25", session_time: "14:00", duration_minutes: 45, location: "Studio B", description: null, notes: "", created_at: "2026-05-19" },
      { id: "3", athlete_name: "Tom Harris", athlete_avatar: "", session_type: "One-on-One", coach_name: "Emily Davis (HIIT)", date_time: "May 24, 2026 09:00 AM", status: "COMPLETED", appointment_date: "2026-05-24", session_time: "09:00", duration_minutes: 60, location: "Studio A", description: null, notes: "", created_at: "2026-05-18" },
      { id: "4", athlete_name: "Sophia Lee", athlete_avatar: "", session_type: "Nutrition Consult", coach_name: "Lisa Thompson (Nutrition)", date_time: "May 24, 2026 11:30 AM", status: "COMPLETED", appointment_date: "2026-05-24", session_time: "11:30", duration_minutes: 30, location: "Online", description: null, notes: "", created_at: "2026-05-17" },
      { id: "5", athlete_name: "Daniel Kim", athlete_avatar: "", session_type: "One-on-One", coach_name: "Alex Rivera (Boxing)", date_time: "May 26, 2026 08:00 AM", status: "PENDING", appointment_date: "2026-05-26", session_time: "08:00", duration_minutes: 60, location: "Studio C", description: null, notes: "", created_at: "2026-05-16" },
      { id: "6", athlete_name: "Emma Brown", athlete_avatar: "", session_type: "Group Class", coach_name: "Sarah Johnson (Strength)", date_time: "May 23, 2026 05:00 PM", status: "CANCELLED", appointment_date: "2026-05-23", session_time: "17:00", duration_minutes: 45, location: "Main Hall", description: null, notes: "Client requested cancellation", created_at: "2026-05-15" },
      { id: "7", athlete_name: "Ryan Patel", athlete_avatar: "", session_type: "One-on-One", coach_name: "Mike Chen (Yoga)", date_time: "May 26, 2026 04:00 PM", status: "UPCOMING", appointment_date: "2026-05-26", session_time: "16:00", duration_minutes: 60, location: "Studio B", description: null, notes: "", created_at: "2026-05-14" },
      { id: "8", athlete_name: "Olivia Turner", athlete_avatar: "", session_type: "Recovery Session", coach_name: "Emily Davis (HIIT)", date_time: "May 25, 2026 07:00 PM", status: "CONFIRMED", appointment_date: "2026-05-25", session_time: "19:00", duration_minutes: 30, location: "Recovery Room", description: null, notes: "", created_at: "2026-05-13" },
      { id: "9", athlete_name: "Liam White", athlete_avatar: "", session_type: "One-on-One", coach_name: "Alex Rivera (Boxing)", date_time: "May 27, 2026 10:30 AM", status: "PENDING", appointment_date: "2026-05-27", session_time: "10:30", duration_minutes: 60, location: "Studio C", description: null, notes: "", created_at: "2026-05-12" },
      { id: "10", athlete_name: "Ava Martinez", athlete_avatar: "", session_type: "Nutrition Consult", coach_name: "Lisa Thompson (Nutrition)", date_time: "May 24, 2026 03:00 PM", status: "COMPLETED", appointment_date: "2026-05-24", session_time: "15:00", duration_minutes: 30, location: "Online", description: null, notes: "", created_at: "2026-05-11" },
    ],
    pagination: { page: 1, limit: 10, total: 10, total_pages: 1, has_next_page: false, has_previous_page: false },
  },
  success: true,
  statusCode: 200,
  message: "Success",
};

export const DEMO_PERFORMANCE_METRICS = {
  data: {
    total_bookings_today: { value: 12, change: 8, is_positive: true, unit: "%" },
    completion_rate: { value: 87, change: 3, is_positive: true, unit: "%" },
    average_session_duration: { value: 52, change: 2, is_positive: true, unit: " min" },
    cancellation_rate: { value: 13, change: 5, is_positive: false, unit: "%" },
  },
};

export const DEMO_USER_LIST = {
  data: {
    data: [
      { id: "1", user_name: "Alice Johnson", role: "Coach", email: "alice.johnson@example.com", joining_date: "2024-01-15", status: "Active", avatar: "" },
      { id: "2", user_name: "Bob Smith", role: "Athlete", email: "bob.smith@example.com", joining_date: "2024-02-20", status: "Active", avatar: "" },
      { id: "3", user_name: "Carol Williams", role: "Athlete", email: "carol.williams@example.com", joining_date: "2024-03-10", status: "Blocked", avatar: "" },
      { id: "4", user_name: "David Brown", role: "Coach", email: "david.brown@example.com", joining_date: "2024-01-05", status: "Active", avatar: "" },
      { id: "5", user_name: "Eva Martinez", role: "Athlete", email: "eva.martinez@example.com", joining_date: "2024-04-12", status: "Active", avatar: "" },
      { id: "6", user_name: "Frank Lee", role: "Admin", email: "frank.lee@example.com", joining_date: "2023-11-01", status: "Active", avatar: "" },
      { id: "7", user_name: "Grace Kim", role: "Athlete", email: "grace.kim@example.com", joining_date: "2024-05-22", status: "Blocked", avatar: "" },
      { id: "8", user_name: "Henry Davis", role: "Coach", email: "henry.davis@example.com", joining_date: "2024-02-14", status: "Active", avatar: "" },
      { id: "9", user_name: "Ivy Chen", role: "Athlete", email: "ivy.chen@example.com", joining_date: "2024-06-01", status: "Active", avatar: "" },
      { id: "10", user_name: "Jack Wilson", role: "Athlete", email: "jack.wilson@example.com", joining_date: "2024-03-28", status: "Active", avatar: "" },
    ],
    pagination: {
      page: 1,
      limit: 10,
      total: 10,
      total_pages: 1,
      has_next_page: false,
      has_previous_page: false,
    },
  },
};

export const demoData = [
  {
    id: "1",
    full_name: "Leslie Alexander",
    email_address: "felicia.reid@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882918803",
    createdAt: "2014-05-30T00:00:00Z",
    time: "2014-05-30T10:30:00Z",
    additional_information: "Website",
    status: "Pre Application",
  },
  {
    id: "2",
    full_name: "Devon Lane",
    email_address: "bill.sanders@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+18102458249",
    createdAt: "2015-05-27T00:00:00Z",
    time: "2015-05-27T14:15:00Z",
    additional_information: "Phone Call",
    status: "Applied",
  },
  {
    id: "3",
    full_name: "Eleanor Pena",
    email_address: "georgia.young@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882918803",
    createdAt: "2012-02-11T00:00:00Z",
    time: "2012-02-11T09:00:00Z",
    additional_information: "Facebook",
    status: "Pre Application",
  },
  {
    id: "4",
    full_name: "Kathryn Murphy",
    email_address: "jessica.hanson@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+14884608141",
    createdAt: "2014-01-14T00:00:00Z",
    time: "2014-01-14T16:45:00Z",
    additional_information: "Email",
    status: "Applied",
  },
  {
    id: "5",
    full_name: "Robert Fox",
    email_address: "nathan.roberts@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882634865",
    createdAt: "2014-08-30T00:00:00Z",
    time: "2014-08-30T11:20:00Z",
    additional_information: "WhatsApp",
    status: "Pre Application",
  },
  {
    id: "6",
    full_name: "Ronald Richards",
    email_address: "tanya.hill@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+14884145917",
    createdAt: "2016-09-18T00:00:00Z",
    time: "2016-09-18T13:30:00Z",
    additional_information: "Website",
    status: "Pending",
  },
  {
    id: "7",
    full_name: "Bessie Cooper",
    email_address: "kenzi.lawson@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+19143008346",
    createdAt: "2013-12-10T00:00:00Z",
    time: "2013-12-10T08:00:00Z",
    additional_information: "Referral",
    status: "Pre Application",
  },
  {
    id: "8",
    full_name: "Cameron Williamson",
    email_address: "willie.jennings@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+14882634869",
    createdAt: "2013-10-08T00:00:00Z",
    time: "2013-10-08T15:45:00Z",
    additional_information: "Instagram",
    status: "Pre Application",
  },
  {
    id: "9",
    full_name: "Wade Warren",
    email_address: "dolores.chambers@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+14882820363",
    createdAt: "2013-07-27T00:00:00Z",
    time: "2013-07-27T10:30:00Z",
    additional_information: "Email",
    status: "Inactive",
  },
  {
    id: "10",
    full_name: "Ralph Edwards",
    email_address: "nevaeh.simmons@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "employer",
    mobile_number: "+18102448985",
    createdAt: "2017-08-16T00:00:00Z",
    time: "2017-08-16T14:20:00Z",
    additional_information: "Website",
    status: "Applied",
  },
  {
    id: "11",
    full_name: "Marvin McKinney",
    email_address: "tim.jennings@example.com",
    actor: "Sarah Meadors",
    time_in_status: "6 minutes, 39 seconds",
    note: "Complete",
    type: "Add Document to User",
    details:
      "Document Client Agency Agreement Placement Fee & Refund Policy was added to user Sabrina Sultana",
    reason: " when client status was changed to",
    changed_by: "Sarah Meadors",
    enquiry_type: "maid",
    mobile_number: "+19143008184",
    createdAt: "2016-09-23T00:00:00Z",
    time: "2016-09-23T09:15:00Z",
    additional_information: "Phone Call",
    status: "Pre Application",
  
  },
];
